import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const vaultPath = "C:/dev/_Obsidian/.obsidian/plugins/passwordblock";

const copyToVault = {
	name: 'copy-to-vault',
	setup(build) {
		build.onEnd(() => {
			if (!fs.existsSync(vaultPath)) {
				fs.mkdirSync(vaultPath, { recursive: true });
			}
			fs.copyFileSync("main.js", path.join(vaultPath, "main.js"));
			fs.copyFileSync("manifest.json", path.join(vaultPath, "manifest.json"));
			fs.copyFileSync("styles.css", path.join(vaultPath, "styles.css"));
			console.log(`Build copied to vault: ${vaultPath}`);
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	plugins: [copyToVault],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
